### ISSUE TITLE
 ReplyError: OOM command not allowed when used memory > 'maxmemory'.

### ISSUE THREAD

**Issue by milesalex** [bee-queue/arena#115]
```
BRPOPLPUSH { ReplyError: OOM command not allowed when used memory > 'maxmemory'.
    at JavascriptRedisParser.returnError (/app/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/app/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:639:20)
  name: 'ReplyError',
  message: 'OOM command not allowed when used memory > \'maxmemory\'.',
  command:
   { name: 'brpoplpush',
     args: [ 'bull:upload json:wait', 'bull:upload json:active', '5' ] } }
```

**Comment by ttacon** [comment]
What's the question here? From the stack trace this seems like a `bull` issue and not an `@bee-queue/arena` issue?
