### ISSUE TITLE
Cannot read property 'id' of null

### ISSUE THREAD

**Issue by jaschaio** [bee-queue/arena#229]
In theory it works well. But when I am trying to display the detailed view of failed jobs I am getting a lot of the Following Error within the logs:

```
(node:7361) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of null
    at /node_modules/bull-arena/src/server/views/dashboard/queueJobsByState.js:100:45
    at Array.map (<anonymous>)
    at _html (/node_modules/bull-arena/src/server/views/dashboard/queueJobsByState.js:99:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The page just never finishes loading.

Not sure why, maybe my jobs are missing a required attribute or something?

Using with `bullmq@1.8.13` and `bull-arena@2.8.1`

**Comment by jaschaio** [comment]
Ok, after a bit of investigation this seems to be more likely a problem with `bullmq`. Will close for now
