### ISSUE TITLE
Crash after click on failed job

### ISSUE THREAD

**Issue by matteomattei** [bee-queue/arena#295]
I have a failed job, I click on it and I obtain the following error in the console:

```
TypeError: Cannot read property 'id' of null
     at /home/matteo/QueueMonitor/node_modules/bull-arena/src/server/views/dashboard/queueJobsByState.js:106:49
     at Array.map (<anonymous>)
     at _html (/home/matteo/QueueMonitor/node_modules/bull-arena/src/server/views/dashboard/queueJobsByState.js:105:12)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by skeggse** [comment]
This mostly sounds like a bug in `bull`. Probably something related to listing jobs that then get removed. Is this a consistent problem? What versions of the packages are you using?

**Comment by matteomattei** [comment]
bull version 3.19.1
bull-arena version 3.6.0

The error happens when I click the "fail" link:

![image](https://user-images.githubusercontent.com/1231122/100374571-c6eb9200-300c-11eb-93c7-501663219614.png)

**Comment by skeggse** [comment]
Thanks for the extra detail. Are you processing a lot of jobs quickly? Is this failed job persisting, or does it come and go?

**Comment by matteomattei** [comment]
It is a job failed due to a missing connection to a remote endpoint in the worker process which resulted to an axios catch block.
