### ISSUE TITLE
Not able to perform delete/select all/remove job from dashboard?

### ISSUE THREAD

**Issue by aditodkar** [bee-queue/arena#503]
I am not able to perform select all/delete/remove job operations on dashboard getting following errors in console.
```
Refused to load the script 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

completed:16 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-nP0EI9B9ad8IoFUti2q7EQBabcE5MS5v0nkvRfUbYnM='), or a nonce ('nonce-...') is required to enable inline execution.

completed:1 Refused to load the script 'https://cdn.jsdelivr.net/combine/npm/jquery@3.5.1,npm/bootstrap@3.4.1/dist/js/bootstrap.min.js' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

bootstrap-treeview.min.js:1 Uncaught ReferenceError: jQuery is not defined
    at bootstrap-treeview.min.js:1:16712
(anonymous) @ bootstrap-treeview.min.js:

dashboard.js:1 Uncaught ReferenceError: $ is not defined
    at dashboard.js:1:1
(anonymous) @ dashboard.js:1

completed:1845 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-zazWTR0XFi1jIhOCA5zyWUjF31uAS1mEMRoegbDT6pU='), or a nonce ('nonce-...') is required to enable inline execution.
```

![Screenshot_1](https://user-images.githubusercontent.com/16613832/159554301-65d1f480-769d-42e8-8017-f56c5d3d82e0.png)

**Comment by ss-southernsun-982** [comment]
Do issue closed? Pleas help me
